version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout # git clone <any repo name>
      - run:
          name: "buuld the service"
          command: |
            echo "hello world"
            ls
            pwd
            cat README.md
  test:
    docker:
      - image: alpine
    steps:
      - run:
          name: "test"
          command: |
            echo "hello this is test step"

workflows:
  welcome:
    jobs:
      - build
      - test:
          requires:
            - build

  